version: '3.8'

services:
  php:
    image: arm64v8/php:7.4-apache   # Updated image for ARM
    container_name: aloo_php
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/var/www/html
      - ./backend:/var/www/backend
    environment:
      - DB_HOST=db
      - DB_DATABASE=AlooTeachDB
      - DB_USERNAME=root
      - DB_PASSWORD=my-secret-pw

  db:
    image: mysql:5.7               # Add platform specification
    platform: linux/amd64           # Forces it to pull a compatible x86_64 image
    container_name: aloo_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: AlooTeachDB
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: aloo_phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=my-secret-pw

volumes:
  db_data:
